//Types
export const types = {
    SHOW_ALL_USERS: 'SHOW_ALL_USERS',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_MORE_USERS: 'GET_MORE_USERS',
    FOLLOW_USER: 'FOLLOW_USER',
    SET_TOTAL_USERS_COUNT: 'SET_TOTAL_USERS_COUNT',

    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_PREV_PAGE: 'SET_PREV_PAGE',
    SET_NEXT_PAGE: 'SET_NEXT_PAGE',
    SET_COUNT_PAGE: 'SET_COUNT_PAGE',
}
